"""empty message

Revision ID: 307b29e9d306
Revises: 5b277fc69a60
Create Date: 2022-03-05 12:16:37.079690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307b29e9d306'
down_revision = '5b277fc69a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
